// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workspace type in the database.
	Label = "workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "workspace_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldActiveTabID holds the string denoting the active_tab_id field in the database.
	FieldActiveTabID = "active_tab_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTabs holds the string denoting the tabs edge name in mutations.
	EdgeTabs = "tabs"
	// WorkspaceTabFieldID holds the string denoting the ID field of the WorkspaceTab.
	WorkspaceTabFieldID = "tab_id"
	// Table holds the table name of the workspace in the database.
	Table = "workspaces"
	// TabsTable is the table that holds the tabs relation/edge.
	TabsTable = "workspace_tabs"
	// TabsInverseTable is the table name for the WorkspaceTab entity.
	// It exists in this package in order to avoid circular dependency with the "workspacetab" package.
	TabsInverseTable = "workspace_tabs"
	// TabsColumn is the table column denoting the tabs relation/edge.
	TabsColumn = "workspace_id"
)

// Columns holds all SQL columns for workspace fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldName,
	FieldActiveTabID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	ProjectIDValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultActiveTabID holds the default value on creation for the "active_tab_id" field.
	DefaultActiveTabID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Workspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByActiveTabID orders the results by the active_tab_id field.
func ByActiveTabID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveTabID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTabsCount orders the results by tabs count.
func ByTabsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTabsStep(), opts...)
	}
}

// ByTabs orders the results by tabs terms.
func ByTabs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTabsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTabsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TabsInverseTable, WorkspaceTabFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TabsTable, TabsColumn),
	)
}
