// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/artifact"
	"insightify/internal/gateway/ent/project"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArtifactCreate is the builder for creating a Artifact entity.
type ArtifactCreate struct {
	config
	mutation *ArtifactMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProjectID sets the "project_id" field.
func (_c *ArtifactCreate) SetProjectID(v string) *ArtifactCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *ArtifactCreate) SetRunID(v string) *ArtifactCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *ArtifactCreate) SetPath(v string) *ArtifactCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArtifactCreate) SetCreatedAt(v time.Time) *ArtifactCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArtifactCreate) SetNillableCreatedAt(v *time.Time) *ArtifactCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ArtifactCreate) SetID(v int) *ArtifactCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ArtifactCreate) SetProject(v *Project) *ArtifactCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ArtifactMutation object of the builder.
func (_c *ArtifactCreate) Mutation() *ArtifactMutation {
	return _c.mutation
}

// Save creates the Artifact in the database.
func (_c *ArtifactCreate) Save(ctx context.Context) (*Artifact, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArtifactCreate) SaveX(ctx context.Context) *Artifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArtifactCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := artifact.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArtifactCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Artifact.project_id"`)}
	}
	if v, ok := _c.mutation.ProjectID(); ok {
		if err := artifact.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Artifact.project_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "Artifact.run_id"`)}
	}
	if v, ok := _c.mutation.RunID(); ok {
		if err := artifact.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Artifact.run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Artifact.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := artifact.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Artifact.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Artifact.created_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Artifact.project"`)}
	}
	return nil
}

func (_c *ArtifactCreate) sqlSave(ctx context.Context) (*Artifact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArtifactCreate) createSpec() (*Artifact, *sqlgraph.CreateSpec) {
	var (
		_node = &Artifact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(artifact.Table, sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(artifact.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(artifact.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(artifact.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifact.ProjectTable,
			Columns: []string{artifact.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Artifact.Create().
//		SetProjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArtifactUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ArtifactCreate) OnConflict(opts ...sql.ConflictOption) *ArtifactUpsertOne {
	_c.conflict = opts
	return &ArtifactUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Artifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArtifactCreate) OnConflictColumns(columns ...string) *ArtifactUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArtifactUpsertOne{
		create: _c,
	}
}

type (
	// ArtifactUpsertOne is the builder for "upsert"-ing
	//  one Artifact node.
	ArtifactUpsertOne struct {
		create *ArtifactCreate
	}

	// ArtifactUpsert is the "OnConflict" setter.
	ArtifactUpsert struct {
		*sql.UpdateSet
	}
)

// SetProjectID sets the "project_id" field.
func (u *ArtifactUpsert) SetProjectID(v string) *ArtifactUpsert {
	u.Set(artifact.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ArtifactUpsert) UpdateProjectID() *ArtifactUpsert {
	u.SetExcluded(artifact.FieldProjectID)
	return u
}

// SetRunID sets the "run_id" field.
func (u *ArtifactUpsert) SetRunID(v string) *ArtifactUpsert {
	u.Set(artifact.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *ArtifactUpsert) UpdateRunID() *ArtifactUpsert {
	u.SetExcluded(artifact.FieldRunID)
	return u
}

// SetPath sets the "path" field.
func (u *ArtifactUpsert) SetPath(v string) *ArtifactUpsert {
	u.Set(artifact.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ArtifactUpsert) UpdatePath() *ArtifactUpsert {
	u.SetExcluded(artifact.FieldPath)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ArtifactUpsert) SetCreatedAt(v time.Time) *ArtifactUpsert {
	u.Set(artifact.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArtifactUpsert) UpdateCreatedAt() *ArtifactUpsert {
	u.SetExcluded(artifact.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Artifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(artifact.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArtifactUpsertOne) UpdateNewValues() *ArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(artifact.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Artifact.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArtifactUpsertOne) Ignore() *ArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArtifactUpsertOne) DoNothing() *ArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArtifactCreate.OnConflict
// documentation for more info.
func (u *ArtifactUpsertOne) Update(set func(*ArtifactUpsert)) *ArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ArtifactUpsertOne) SetProjectID(v string) *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ArtifactUpsertOne) UpdateProjectID() *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdateProjectID()
	})
}

// SetRunID sets the "run_id" field.
func (u *ArtifactUpsertOne) SetRunID(v string) *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *ArtifactUpsertOne) UpdateRunID() *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdateRunID()
	})
}

// SetPath sets the "path" field.
func (u *ArtifactUpsertOne) SetPath(v string) *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ArtifactUpsertOne) UpdatePath() *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdatePath()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ArtifactUpsertOne) SetCreatedAt(v time.Time) *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArtifactUpsertOne) UpdateCreatedAt() *ArtifactUpsertOne {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *ArtifactUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArtifactCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArtifactUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArtifactUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArtifactUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArtifactCreateBulk is the builder for creating many Artifact entities in bulk.
type ArtifactCreateBulk struct {
	config
	err      error
	builders []*ArtifactCreate
	conflict []sql.ConflictOption
}

// Save creates the Artifact entities in the database.
func (_c *ArtifactCreateBulk) Save(ctx context.Context) ([]*Artifact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Artifact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArtifactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArtifactCreateBulk) SaveX(ctx context.Context) []*Artifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Artifact.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArtifactUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ArtifactCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArtifactUpsertBulk {
	_c.conflict = opts
	return &ArtifactUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Artifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArtifactCreateBulk) OnConflictColumns(columns ...string) *ArtifactUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArtifactUpsertBulk{
		create: _c,
	}
}

// ArtifactUpsertBulk is the builder for "upsert"-ing
// a bulk of Artifact nodes.
type ArtifactUpsertBulk struct {
	create *ArtifactCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Artifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(artifact.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArtifactUpsertBulk) UpdateNewValues() *ArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(artifact.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Artifact.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArtifactUpsertBulk) Ignore() *ArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArtifactUpsertBulk) DoNothing() *ArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArtifactCreateBulk.OnConflict
// documentation for more info.
func (u *ArtifactUpsertBulk) Update(set func(*ArtifactUpsert)) *ArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ArtifactUpsertBulk) SetProjectID(v string) *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ArtifactUpsertBulk) UpdateProjectID() *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdateProjectID()
	})
}

// SetRunID sets the "run_id" field.
func (u *ArtifactUpsertBulk) SetRunID(v string) *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *ArtifactUpsertBulk) UpdateRunID() *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdateRunID()
	})
}

// SetPath sets the "path" field.
func (u *ArtifactUpsertBulk) SetPath(v string) *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ArtifactUpsertBulk) UpdatePath() *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdatePath()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ArtifactUpsertBulk) SetCreatedAt(v time.Time) *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArtifactUpsertBulk) UpdateCreatedAt() *ArtifactUpsertBulk {
	return u.Update(func(s *ArtifactUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *ArtifactUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArtifactCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArtifactCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArtifactUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
