// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/artifactfile"
	"insightify/internal/gateway/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArtifactFileUpdate is the builder for updating ArtifactFile entities.
type ArtifactFileUpdate struct {
	config
	hooks    []Hook
	mutation *ArtifactFileMutation
}

// Where appends a list predicates to the ArtifactFileUpdate builder.
func (_u *ArtifactFileUpdate) Where(ps ...predicate.ArtifactFile) *ArtifactFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *ArtifactFileUpdate) SetRunID(v string) *ArtifactFileUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *ArtifactFileUpdate) SetNillableRunID(v *string) *ArtifactFileUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ArtifactFileUpdate) SetPath(v string) *ArtifactFileUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ArtifactFileUpdate) SetNillablePath(v *string) *ArtifactFileUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ArtifactFileUpdate) SetContent(v []byte) *ArtifactFileUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetSize sets the "size" field.
func (_u *ArtifactFileUpdate) SetSize(v int64) *ArtifactFileUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ArtifactFileUpdate) SetNillableSize(v *int64) *ArtifactFileUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ArtifactFileUpdate) AddSize(v int64) *ArtifactFileUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ArtifactFileUpdate) SetCreatedAt(v time.Time) *ArtifactFileUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ArtifactFileUpdate) SetNillableCreatedAt(v *time.Time) *ArtifactFileUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArtifactFileUpdate) SetUpdatedAt(v time.Time) *ArtifactFileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ArtifactFileMutation object of the builder.
func (_u *ArtifactFileUpdate) Mutation() *ArtifactFileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArtifactFileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArtifactFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArtifactFileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := artifactfile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtifactFileUpdate) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := artifactfile.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := artifactfile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := artifactfile.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.size": %w`, err)}
		}
	}
	return nil
}

func (_u *ArtifactFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artifactfile.Table, artifactfile.Columns, sqlgraph.NewFieldSpec(artifactfile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(artifactfile.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(artifactfile.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(artifactfile.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(artifactfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(artifactfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(artifactfile.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifactfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArtifactFileUpdateOne is the builder for updating a single ArtifactFile entity.
type ArtifactFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArtifactFileMutation
}

// SetRunID sets the "run_id" field.
func (_u *ArtifactFileUpdateOne) SetRunID(v string) *ArtifactFileUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *ArtifactFileUpdateOne) SetNillableRunID(v *string) *ArtifactFileUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ArtifactFileUpdateOne) SetPath(v string) *ArtifactFileUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ArtifactFileUpdateOne) SetNillablePath(v *string) *ArtifactFileUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ArtifactFileUpdateOne) SetContent(v []byte) *ArtifactFileUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetSize sets the "size" field.
func (_u *ArtifactFileUpdateOne) SetSize(v int64) *ArtifactFileUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ArtifactFileUpdateOne) SetNillableSize(v *int64) *ArtifactFileUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ArtifactFileUpdateOne) AddSize(v int64) *ArtifactFileUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ArtifactFileUpdateOne) SetCreatedAt(v time.Time) *ArtifactFileUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ArtifactFileUpdateOne) SetNillableCreatedAt(v *time.Time) *ArtifactFileUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArtifactFileUpdateOne) SetUpdatedAt(v time.Time) *ArtifactFileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ArtifactFileMutation object of the builder.
func (_u *ArtifactFileUpdateOne) Mutation() *ArtifactFileMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArtifactFileUpdate builder.
func (_u *ArtifactFileUpdateOne) Where(ps ...predicate.ArtifactFile) *ArtifactFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArtifactFileUpdateOne) Select(field string, fields ...string) *ArtifactFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ArtifactFile entity.
func (_u *ArtifactFileUpdateOne) Save(ctx context.Context) (*ArtifactFile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactFileUpdateOne) SaveX(ctx context.Context) *ArtifactFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArtifactFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArtifactFileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := artifactfile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtifactFileUpdateOne) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := artifactfile.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := artifactfile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := artifactfile.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.size": %w`, err)}
		}
	}
	return nil
}

func (_u *ArtifactFileUpdateOne) sqlSave(ctx context.Context) (_node *ArtifactFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artifactfile.Table, artifactfile.Columns, sqlgraph.NewFieldSpec(artifactfile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArtifactFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artifactfile.FieldID)
		for _, f := range fields {
			if !artifactfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != artifactfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(artifactfile.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(artifactfile.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(artifactfile.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(artifactfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(artifactfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(artifactfile.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactfile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ArtifactFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifactfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
