// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/artifactfile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArtifactFileCreate is the builder for creating a ArtifactFile entity.
type ArtifactFileCreate struct {
	config
	mutation *ArtifactFileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunID sets the "run_id" field.
func (_c *ArtifactFileCreate) SetRunID(v string) *ArtifactFileCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *ArtifactFileCreate) SetPath(v string) *ArtifactFileCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ArtifactFileCreate) SetContent(v []byte) *ArtifactFileCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *ArtifactFileCreate) SetSize(v int64) *ArtifactFileCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArtifactFileCreate) SetCreatedAt(v time.Time) *ArtifactFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArtifactFileCreate) SetNillableCreatedAt(v *time.Time) *ArtifactFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ArtifactFileCreate) SetUpdatedAt(v time.Time) *ArtifactFileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ArtifactFileCreate) SetNillableUpdatedAt(v *time.Time) *ArtifactFileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ArtifactFileCreate) SetID(v int) *ArtifactFileCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ArtifactFileMutation object of the builder.
func (_c *ArtifactFileCreate) Mutation() *ArtifactFileMutation {
	return _c.mutation
}

// Save creates the ArtifactFile in the database.
func (_c *ArtifactFileCreate) Save(ctx context.Context) (*ArtifactFile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArtifactFileCreate) SaveX(ctx context.Context) *ArtifactFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArtifactFileCreate) defaults() {
	if _, ok := _c.mutation.Content(); !ok {
		v := artifactfile.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := artifactfile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := artifactfile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArtifactFileCreate) check() error {
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "ArtifactFile.run_id"`)}
	}
	if v, ok := _c.mutation.RunID(); ok {
		if err := artifactfile.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "ArtifactFile.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := artifactfile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ArtifactFile.content"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "ArtifactFile.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := artifactfile.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ArtifactFile.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArtifactFile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArtifactFile.updated_at"`)}
	}
	return nil
}

func (_c *ArtifactFileCreate) sqlSave(ctx context.Context) (*ArtifactFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArtifactFileCreate) createSpec() (*ArtifactFile, *sqlgraph.CreateSpec) {
	var (
		_node = &ArtifactFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(artifactfile.Table, sqlgraph.NewFieldSpec(artifactfile.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(artifactfile.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(artifactfile.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(artifactfile.FieldContent, field.TypeBytes, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(artifactfile.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(artifactfile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactfile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArtifactFile.Create().
//		SetRunID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArtifactFileUpsert) {
//			SetRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *ArtifactFileCreate) OnConflict(opts ...sql.ConflictOption) *ArtifactFileUpsertOne {
	_c.conflict = opts
	return &ArtifactFileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArtifactFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArtifactFileCreate) OnConflictColumns(columns ...string) *ArtifactFileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArtifactFileUpsertOne{
		create: _c,
	}
}

type (
	// ArtifactFileUpsertOne is the builder for "upsert"-ing
	//  one ArtifactFile node.
	ArtifactFileUpsertOne struct {
		create *ArtifactFileCreate
	}

	// ArtifactFileUpsert is the "OnConflict" setter.
	ArtifactFileUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunID sets the "run_id" field.
func (u *ArtifactFileUpsert) SetRunID(v string) *ArtifactFileUpsert {
	u.Set(artifactfile.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *ArtifactFileUpsert) UpdateRunID() *ArtifactFileUpsert {
	u.SetExcluded(artifactfile.FieldRunID)
	return u
}

// SetPath sets the "path" field.
func (u *ArtifactFileUpsert) SetPath(v string) *ArtifactFileUpsert {
	u.Set(artifactfile.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ArtifactFileUpsert) UpdatePath() *ArtifactFileUpsert {
	u.SetExcluded(artifactfile.FieldPath)
	return u
}

// SetContent sets the "content" field.
func (u *ArtifactFileUpsert) SetContent(v []byte) *ArtifactFileUpsert {
	u.Set(artifactfile.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ArtifactFileUpsert) UpdateContent() *ArtifactFileUpsert {
	u.SetExcluded(artifactfile.FieldContent)
	return u
}

// SetSize sets the "size" field.
func (u *ArtifactFileUpsert) SetSize(v int64) *ArtifactFileUpsert {
	u.Set(artifactfile.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ArtifactFileUpsert) UpdateSize() *ArtifactFileUpsert {
	u.SetExcluded(artifactfile.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *ArtifactFileUpsert) AddSize(v int64) *ArtifactFileUpsert {
	u.Add(artifactfile.FieldSize, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ArtifactFileUpsert) SetCreatedAt(v time.Time) *ArtifactFileUpsert {
	u.Set(artifactfile.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArtifactFileUpsert) UpdateCreatedAt() *ArtifactFileUpsert {
	u.SetExcluded(artifactfile.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArtifactFileUpsert) SetUpdatedAt(v time.Time) *ArtifactFileUpsert {
	u.Set(artifactfile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArtifactFileUpsert) UpdateUpdatedAt() *ArtifactFileUpsert {
	u.SetExcluded(artifactfile.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ArtifactFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(artifactfile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArtifactFileUpsertOne) UpdateNewValues() *ArtifactFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(artifactfile.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArtifactFile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArtifactFileUpsertOne) Ignore() *ArtifactFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArtifactFileUpsertOne) DoNothing() *ArtifactFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArtifactFileCreate.OnConflict
// documentation for more info.
func (u *ArtifactFileUpsertOne) Update(set func(*ArtifactFileUpsert)) *ArtifactFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArtifactFileUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunID sets the "run_id" field.
func (u *ArtifactFileUpsertOne) SetRunID(v string) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *ArtifactFileUpsertOne) UpdateRunID() *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateRunID()
	})
}

// SetPath sets the "path" field.
func (u *ArtifactFileUpsertOne) SetPath(v string) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ArtifactFileUpsertOne) UpdatePath() *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdatePath()
	})
}

// SetContent sets the "content" field.
func (u *ArtifactFileUpsertOne) SetContent(v []byte) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ArtifactFileUpsertOne) UpdateContent() *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateContent()
	})
}

// SetSize sets the "size" field.
func (u *ArtifactFileUpsertOne) SetSize(v int64) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ArtifactFileUpsertOne) AddSize(v int64) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ArtifactFileUpsertOne) UpdateSize() *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateSize()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ArtifactFileUpsertOne) SetCreatedAt(v time.Time) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArtifactFileUpsertOne) UpdateCreatedAt() *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArtifactFileUpsertOne) SetUpdatedAt(v time.Time) *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArtifactFileUpsertOne) UpdateUpdatedAt() *ArtifactFileUpsertOne {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ArtifactFileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArtifactFileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArtifactFileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArtifactFileUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArtifactFileUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArtifactFileCreateBulk is the builder for creating many ArtifactFile entities in bulk.
type ArtifactFileCreateBulk struct {
	config
	err      error
	builders []*ArtifactFileCreate
	conflict []sql.ConflictOption
}

// Save creates the ArtifactFile entities in the database.
func (_c *ArtifactFileCreateBulk) Save(ctx context.Context) ([]*ArtifactFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ArtifactFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArtifactFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArtifactFileCreateBulk) SaveX(ctx context.Context) []*ArtifactFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArtifactFile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArtifactFileUpsert) {
//			SetRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *ArtifactFileCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArtifactFileUpsertBulk {
	_c.conflict = opts
	return &ArtifactFileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArtifactFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArtifactFileCreateBulk) OnConflictColumns(columns ...string) *ArtifactFileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArtifactFileUpsertBulk{
		create: _c,
	}
}

// ArtifactFileUpsertBulk is the builder for "upsert"-ing
// a bulk of ArtifactFile nodes.
type ArtifactFileUpsertBulk struct {
	create *ArtifactFileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ArtifactFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(artifactfile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArtifactFileUpsertBulk) UpdateNewValues() *ArtifactFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(artifactfile.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArtifactFile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArtifactFileUpsertBulk) Ignore() *ArtifactFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArtifactFileUpsertBulk) DoNothing() *ArtifactFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArtifactFileCreateBulk.OnConflict
// documentation for more info.
func (u *ArtifactFileUpsertBulk) Update(set func(*ArtifactFileUpsert)) *ArtifactFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArtifactFileUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunID sets the "run_id" field.
func (u *ArtifactFileUpsertBulk) SetRunID(v string) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *ArtifactFileUpsertBulk) UpdateRunID() *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateRunID()
	})
}

// SetPath sets the "path" field.
func (u *ArtifactFileUpsertBulk) SetPath(v string) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ArtifactFileUpsertBulk) UpdatePath() *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdatePath()
	})
}

// SetContent sets the "content" field.
func (u *ArtifactFileUpsertBulk) SetContent(v []byte) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ArtifactFileUpsertBulk) UpdateContent() *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateContent()
	})
}

// SetSize sets the "size" field.
func (u *ArtifactFileUpsertBulk) SetSize(v int64) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ArtifactFileUpsertBulk) AddSize(v int64) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ArtifactFileUpsertBulk) UpdateSize() *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateSize()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ArtifactFileUpsertBulk) SetCreatedAt(v time.Time) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArtifactFileUpsertBulk) UpdateCreatedAt() *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArtifactFileUpsertBulk) SetUpdatedAt(v time.Time) *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArtifactFileUpsertBulk) UpdateUpdatedAt() *ArtifactFileUpsertBulk {
	return u.Update(func(s *ArtifactFileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ArtifactFileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArtifactFileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArtifactFileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArtifactFileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
