// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/artifact"
	"insightify/internal/gateway/ent/predicate"
	"insightify/internal/gateway/ent/project"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArtifactUpdate is the builder for updating Artifact entities.
type ArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *ArtifactMutation
}

// Where appends a list predicates to the ArtifactUpdate builder.
func (_u *ArtifactUpdate) Where(ps ...predicate.Artifact) *ArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *ArtifactUpdate) SetRunID(v string) *ArtifactUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableRunID(v *string) *ArtifactUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ArtifactUpdate) SetPath(v string) *ArtifactUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillablePath(v *string) *ArtifactUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ArtifactUpdate) SetCreatedAt(v time.Time) *ArtifactUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableCreatedAt(v *time.Time) *ArtifactUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ArtifactUpdate) SetProjectID(id string) *ArtifactUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableProjectID(id *string) *ArtifactUpdate {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ArtifactUpdate) SetProject(v *Project) *ArtifactUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ArtifactMutation object of the builder.
func (_u *ArtifactUpdate) Mutation() *ArtifactMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ArtifactUpdate) ClearProject() *ArtifactUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArtifactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtifactUpdate) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := artifact.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Artifact.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := artifact.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Artifact.path": %w`, err)}
		}
	}
	return nil
}

func (_u *ArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artifact.Table, artifact.Columns, sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(artifact.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(artifact.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(artifact.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifact.ProjectTable,
			Columns: []string{artifact.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifact.ProjectTable,
			Columns: []string{artifact.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArtifactUpdateOne is the builder for updating a single Artifact entity.
type ArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArtifactMutation
}

// SetRunID sets the "run_id" field.
func (_u *ArtifactUpdateOne) SetRunID(v string) *ArtifactUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableRunID(v *string) *ArtifactUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ArtifactUpdateOne) SetPath(v string) *ArtifactUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillablePath(v *string) *ArtifactUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ArtifactUpdateOne) SetCreatedAt(v time.Time) *ArtifactUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableCreatedAt(v *time.Time) *ArtifactUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ArtifactUpdateOne) SetProjectID(id string) *ArtifactUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableProjectID(id *string) *ArtifactUpdateOne {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ArtifactUpdateOne) SetProject(v *Project) *ArtifactUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ArtifactMutation object of the builder.
func (_u *ArtifactUpdateOne) Mutation() *ArtifactMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ArtifactUpdateOne) ClearProject() *ArtifactUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ArtifactUpdate builder.
func (_u *ArtifactUpdateOne) Where(ps ...predicate.Artifact) *ArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArtifactUpdateOne) Select(field string, fields ...string) *ArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Artifact entity.
func (_u *ArtifactUpdateOne) Save(ctx context.Context) (*Artifact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactUpdateOne) SaveX(ctx context.Context) *Artifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := artifact.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Artifact.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := artifact.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Artifact.path": %w`, err)}
		}
	}
	return nil
}

func (_u *ArtifactUpdateOne) sqlSave(ctx context.Context) (_node *Artifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artifact.Table, artifact.Columns, sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Artifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artifact.FieldID)
		for _, f := range fields {
			if !artifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != artifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(artifact.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(artifact.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(artifact.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifact.ProjectTable,
			Columns: []string{artifact.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifact.ProjectTable,
			Columns: []string{artifact.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Artifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
