// Code generated by ent, DO NOT EDIT.

package ent

import (
	"insightify/internal/gateway/ent/artifact"
	"insightify/internal/gateway/ent/project"
	"insightify/internal/gateway/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	artifactFields := schema.Artifact{}.Fields()
	_ = artifactFields
	// artifactDescRunID is the schema descriptor for run_id field.
	artifactDescRunID := artifactFields[1].Descriptor()
	// artifact.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	artifact.RunIDValidator = artifactDescRunID.Validators[0].(func(string) error)
	// artifactDescPath is the schema descriptor for path field.
	artifactDescPath := artifactFields[2].Descriptor()
	// artifact.PathValidator is a validator for the "path" field. It is called by the builders before save.
	artifact.PathValidator = artifactDescPath.Validators[0].(func(string) error)
	// artifactDescCreatedAt is the schema descriptor for created_at field.
	artifactDescCreatedAt := artifactFields[3].Descriptor()
	// artifact.DefaultCreatedAt holds the default value on creation for the created_at field.
	artifact.DefaultCreatedAt = artifactDescCreatedAt.Default.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[1].Descriptor()
	// project.DefaultName holds the default value on creation for the name field.
	project.DefaultName = projectDescName.Default.(string)
	// projectDescUserID is the schema descriptor for user_id field.
	projectDescUserID := projectFields[2].Descriptor()
	// project.DefaultUserID holds the default value on creation for the user_id field.
	project.DefaultUserID = projectDescUserID.Default.(string)
	// projectDescRepo is the schema descriptor for repo field.
	projectDescRepo := projectFields[3].Descriptor()
	// project.DefaultRepo holds the default value on creation for the repo field.
	project.DefaultRepo = projectDescRepo.Default.(string)
	// projectDescIsActive is the schema descriptor for is_active field.
	projectDescIsActive := projectFields[4].Descriptor()
	// project.DefaultIsActive holds the default value on creation for the is_active field.
	project.DefaultIsActive = projectDescIsActive.Default.(bool)
}
