// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/userinteraction"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserInteractionCreate is the builder for creating a UserInteraction entity.
type UserInteractionCreate struct {
	config
	mutation *UserInteractionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVersion sets the "version" field.
func (_c *UserInteractionCreate) SetVersion(v int64) *UserInteractionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *UserInteractionCreate) SetNillableVersion(v *int64) *UserInteractionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetNodes sets the "nodes" field.
func (_c *UserInteractionCreate) SetNodes(v map[string]interface{}) *UserInteractionCreate {
	_c.mutation.SetNodes(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserInteractionCreate) SetCreatedAt(v time.Time) *UserInteractionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserInteractionCreate) SetNillableCreatedAt(v *time.Time) *UserInteractionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserInteractionCreate) SetUpdatedAt(v time.Time) *UserInteractionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserInteractionCreate) SetNillableUpdatedAt(v *time.Time) *UserInteractionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserInteractionCreate) SetID(v string) *UserInteractionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserInteractionMutation object of the builder.
func (_c *UserInteractionCreate) Mutation() *UserInteractionMutation {
	return _c.mutation
}

// Save creates the UserInteraction in the database.
func (_c *UserInteractionCreate) Save(ctx context.Context) (*UserInteraction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserInteractionCreate) SaveX(ctx context.Context) *UserInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserInteractionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserInteractionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserInteractionCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := userinteraction.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Nodes(); !ok {
		v := userinteraction.DefaultNodes
		_c.mutation.SetNodes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userinteraction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userinteraction.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserInteractionCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "UserInteraction.version"`)}
	}
	if _, ok := _c.mutation.Nodes(); !ok {
		return &ValidationError{Name: "nodes", err: errors.New(`ent: missing required field "UserInteraction.nodes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserInteraction.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserInteraction.updated_at"`)}
	}
	return nil
}

func (_c *UserInteractionCreate) sqlSave(ctx context.Context) (*UserInteraction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserInteraction.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserInteractionCreate) createSpec() (*UserInteraction, *sqlgraph.CreateSpec) {
	var (
		_node = &UserInteraction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userinteraction.Table, sqlgraph.NewFieldSpec(userinteraction.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(userinteraction.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Nodes(); ok {
		_spec.SetField(userinteraction.FieldNodes, field.TypeJSON, value)
		_node.Nodes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userinteraction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userinteraction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserInteraction.Create().
//		SetVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserInteractionUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *UserInteractionCreate) OnConflict(opts ...sql.ConflictOption) *UserInteractionUpsertOne {
	_c.conflict = opts
	return &UserInteractionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserInteraction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserInteractionCreate) OnConflictColumns(columns ...string) *UserInteractionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserInteractionUpsertOne{
		create: _c,
	}
}

type (
	// UserInteractionUpsertOne is the builder for "upsert"-ing
	//  one UserInteraction node.
	UserInteractionUpsertOne struct {
		create *UserInteractionCreate
	}

	// UserInteractionUpsert is the "OnConflict" setter.
	UserInteractionUpsert struct {
		*sql.UpdateSet
	}
)

// SetVersion sets the "version" field.
func (u *UserInteractionUpsert) SetVersion(v int64) *UserInteractionUpsert {
	u.Set(userinteraction.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserInteractionUpsert) UpdateVersion() *UserInteractionUpsert {
	u.SetExcluded(userinteraction.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *UserInteractionUpsert) AddVersion(v int64) *UserInteractionUpsert {
	u.Add(userinteraction.FieldVersion, v)
	return u
}

// SetNodes sets the "nodes" field.
func (u *UserInteractionUpsert) SetNodes(v map[string]interface{}) *UserInteractionUpsert {
	u.Set(userinteraction.FieldNodes, v)
	return u
}

// UpdateNodes sets the "nodes" field to the value that was provided on create.
func (u *UserInteractionUpsert) UpdateNodes() *UserInteractionUpsert {
	u.SetExcluded(userinteraction.FieldNodes)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UserInteractionUpsert) SetCreatedAt(v time.Time) *UserInteractionUpsert {
	u.Set(userinteraction.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserInteractionUpsert) UpdateCreatedAt() *UserInteractionUpsert {
	u.SetExcluded(userinteraction.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserInteractionUpsert) SetUpdatedAt(v time.Time) *UserInteractionUpsert {
	u.Set(userinteraction.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserInteractionUpsert) UpdateUpdatedAt() *UserInteractionUpsert {
	u.SetExcluded(userinteraction.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserInteraction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userinteraction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserInteractionUpsertOne) UpdateNewValues() *UserInteractionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userinteraction.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserInteraction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserInteractionUpsertOne) Ignore() *UserInteractionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserInteractionUpsertOne) DoNothing() *UserInteractionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserInteractionCreate.OnConflict
// documentation for more info.
func (u *UserInteractionUpsertOne) Update(set func(*UserInteractionUpsert)) *UserInteractionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserInteractionUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *UserInteractionUpsertOne) SetVersion(v int64) *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserInteractionUpsertOne) AddVersion(v int64) *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserInteractionUpsertOne) UpdateVersion() *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateVersion()
	})
}

// SetNodes sets the "nodes" field.
func (u *UserInteractionUpsertOne) SetNodes(v map[string]interface{}) *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetNodes(v)
	})
}

// UpdateNodes sets the "nodes" field to the value that was provided on create.
func (u *UserInteractionUpsertOne) UpdateNodes() *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateNodes()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserInteractionUpsertOne) SetCreatedAt(v time.Time) *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserInteractionUpsertOne) UpdateCreatedAt() *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserInteractionUpsertOne) SetUpdatedAt(v time.Time) *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserInteractionUpsertOne) UpdateUpdatedAt() *UserInteractionUpsertOne {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserInteractionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserInteractionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserInteractionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserInteractionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserInteractionUpsertOne.ID is not supported by MySQL driver. Use UserInteractionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserInteractionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserInteractionCreateBulk is the builder for creating many UserInteraction entities in bulk.
type UserInteractionCreateBulk struct {
	config
	err      error
	builders []*UserInteractionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserInteraction entities in the database.
func (_c *UserInteractionCreateBulk) Save(ctx context.Context) ([]*UserInteraction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserInteraction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserInteractionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserInteractionCreateBulk) SaveX(ctx context.Context) []*UserInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserInteractionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserInteractionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserInteraction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserInteractionUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *UserInteractionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserInteractionUpsertBulk {
	_c.conflict = opts
	return &UserInteractionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserInteraction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserInteractionCreateBulk) OnConflictColumns(columns ...string) *UserInteractionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserInteractionUpsertBulk{
		create: _c,
	}
}

// UserInteractionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserInteraction nodes.
type UserInteractionUpsertBulk struct {
	create *UserInteractionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserInteraction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userinteraction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserInteractionUpsertBulk) UpdateNewValues() *UserInteractionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userinteraction.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserInteraction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserInteractionUpsertBulk) Ignore() *UserInteractionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserInteractionUpsertBulk) DoNothing() *UserInteractionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserInteractionCreateBulk.OnConflict
// documentation for more info.
func (u *UserInteractionUpsertBulk) Update(set func(*UserInteractionUpsert)) *UserInteractionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserInteractionUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *UserInteractionUpsertBulk) SetVersion(v int64) *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserInteractionUpsertBulk) AddVersion(v int64) *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserInteractionUpsertBulk) UpdateVersion() *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateVersion()
	})
}

// SetNodes sets the "nodes" field.
func (u *UserInteractionUpsertBulk) SetNodes(v map[string]interface{}) *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetNodes(v)
	})
}

// UpdateNodes sets the "nodes" field to the value that was provided on create.
func (u *UserInteractionUpsertBulk) UpdateNodes() *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateNodes()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserInteractionUpsertBulk) SetCreatedAt(v time.Time) *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserInteractionUpsertBulk) UpdateCreatedAt() *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserInteractionUpsertBulk) SetUpdatedAt(v time.Time) *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserInteractionUpsertBulk) UpdateUpdatedAt() *UserInteractionUpsertBulk {
	return u.Update(func(s *UserInteractionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserInteractionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserInteractionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserInteractionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserInteractionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
