// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/predicate"
	"insightify/internal/gateway/ent/userinteraction"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserInteractionUpdate is the builder for updating UserInteraction entities.
type UserInteractionUpdate struct {
	config
	hooks    []Hook
	mutation *UserInteractionMutation
}

// Where appends a list predicates to the UserInteractionUpdate builder.
func (_u *UserInteractionUpdate) Where(ps ...predicate.UserInteraction) *UserInteractionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserInteractionUpdate) SetVersion(v int64) *UserInteractionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserInteractionUpdate) SetNillableVersion(v *int64) *UserInteractionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserInteractionUpdate) AddVersion(v int64) *UserInteractionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetNodes sets the "nodes" field.
func (_u *UserInteractionUpdate) SetNodes(v map[string]interface{}) *UserInteractionUpdate {
	_u.mutation.SetNodes(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserInteractionUpdate) SetCreatedAt(v time.Time) *UserInteractionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserInteractionUpdate) SetNillableCreatedAt(v *time.Time) *UserInteractionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserInteractionUpdate) SetUpdatedAt(v time.Time) *UserInteractionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserInteractionMutation object of the builder.
func (_u *UserInteractionUpdate) Mutation() *UserInteractionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserInteractionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserInteractionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserInteractionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserInteractionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserInteractionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userinteraction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserInteractionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userinteraction.Table, userinteraction.Columns, sqlgraph.NewFieldSpec(userinteraction.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(userinteraction.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(userinteraction.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Nodes(); ok {
		_spec.SetField(userinteraction.FieldNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userinteraction.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userinteraction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userinteraction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserInteractionUpdateOne is the builder for updating a single UserInteraction entity.
type UserInteractionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserInteractionMutation
}

// SetVersion sets the "version" field.
func (_u *UserInteractionUpdateOne) SetVersion(v int64) *UserInteractionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserInteractionUpdateOne) SetNillableVersion(v *int64) *UserInteractionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserInteractionUpdateOne) AddVersion(v int64) *UserInteractionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetNodes sets the "nodes" field.
func (_u *UserInteractionUpdateOne) SetNodes(v map[string]interface{}) *UserInteractionUpdateOne {
	_u.mutation.SetNodes(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserInteractionUpdateOne) SetCreatedAt(v time.Time) *UserInteractionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserInteractionUpdateOne) SetNillableCreatedAt(v *time.Time) *UserInteractionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserInteractionUpdateOne) SetUpdatedAt(v time.Time) *UserInteractionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserInteractionMutation object of the builder.
func (_u *UserInteractionUpdateOne) Mutation() *UserInteractionMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserInteractionUpdate builder.
func (_u *UserInteractionUpdateOne) Where(ps ...predicate.UserInteraction) *UserInteractionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserInteractionUpdateOne) Select(field string, fields ...string) *UserInteractionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserInteraction entity.
func (_u *UserInteractionUpdateOne) Save(ctx context.Context) (*UserInteraction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserInteractionUpdateOne) SaveX(ctx context.Context) *UserInteraction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserInteractionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserInteractionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserInteractionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userinteraction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserInteractionUpdateOne) sqlSave(ctx context.Context) (_node *UserInteraction, err error) {
	_spec := sqlgraph.NewUpdateSpec(userinteraction.Table, userinteraction.Columns, sqlgraph.NewFieldSpec(userinteraction.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserInteraction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userinteraction.FieldID)
		for _, f := range fields {
			if !userinteraction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userinteraction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(userinteraction.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(userinteraction.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Nodes(); ok {
		_spec.SetField(userinteraction.FieldNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userinteraction.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userinteraction.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserInteraction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userinteraction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
