// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"insightify/internal/gateway/ent/workspace"
	"insightify/internal/gateway/ent/workspacetab"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WorkspaceTab is the model entity for the WorkspaceTab schema.
type WorkspaceTab struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// OrderIndex holds the value of the "order_index" field.
	OrderIndex int `json:"order_index,omitempty"`
	// IsPinned holds the value of the "is_pinned" field.
	IsPinned bool `json:"is_pinned,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkspaceTabQuery when eager-loading is set.
	Edges        WorkspaceTabEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkspaceTabEdges holds the relations/edges for other nodes in the graph.
type WorkspaceTabEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkspaceTabEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkspaceTab) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspacetab.FieldIsPinned:
			values[i] = new(sql.NullBool)
		case workspacetab.FieldOrderIndex:
			values[i] = new(sql.NullInt64)
		case workspacetab.FieldID, workspacetab.FieldWorkspaceID, workspacetab.FieldTitle, workspacetab.FieldRunID:
			values[i] = new(sql.NullString)
		case workspacetab.FieldCreatedAt, workspacetab.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkspaceTab fields.
func (_m *WorkspaceTab) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspacetab.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case workspacetab.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = value.String
			}
		case workspacetab.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case workspacetab.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case workspacetab.FieldOrderIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_index", values[i])
			} else if value.Valid {
				_m.OrderIndex = int(value.Int64)
			}
		case workspacetab.FieldIsPinned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_pinned", values[i])
			} else if value.Valid {
				_m.IsPinned = value.Bool
			}
		case workspacetab.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case workspacetab.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkspaceTab.
// This includes values selected through modifiers, order, etc.
func (_m *WorkspaceTab) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the WorkspaceTab entity.
func (_m *WorkspaceTab) QueryWorkspace() *WorkspaceQuery {
	return NewWorkspaceTabClient(_m.config).QueryWorkspace(_m)
}

// Update returns a builder for updating this WorkspaceTab.
// Note that you need to call WorkspaceTab.Unwrap() before calling this method if this WorkspaceTab
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkspaceTab) Update() *WorkspaceTabUpdateOne {
	return NewWorkspaceTabClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkspaceTab entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkspaceTab) Unwrap() *WorkspaceTab {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkspaceTab is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkspaceTab) String() string {
	var builder strings.Builder
	builder.WriteString("WorkspaceTab(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(_m.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("order_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIndex))
	builder.WriteString(", ")
	builder.WriteString("is_pinned=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPinned))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkspaceTabs is a parsable slice of WorkspaceTab.
type WorkspaceTabs []*WorkspaceTab
