// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/workspace"
	"insightify/internal/gateway/ent/workspacetab"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceTabCreate is the builder for creating a WorkspaceTab entity.
type WorkspaceTabCreate struct {
	config
	mutation *WorkspaceTabMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *WorkspaceTabCreate) SetWorkspaceID(v string) *WorkspaceTabCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *WorkspaceTabCreate) SetTitle(v string) *WorkspaceTabCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *WorkspaceTabCreate) SetNillableTitle(v *string) *WorkspaceTabCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *WorkspaceTabCreate) SetRunID(v string) *WorkspaceTabCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *WorkspaceTabCreate) SetNillableRunID(v *string) *WorkspaceTabCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *WorkspaceTabCreate) SetOrderIndex(v int) *WorkspaceTabCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_c *WorkspaceTabCreate) SetNillableOrderIndex(v *int) *WorkspaceTabCreate {
	if v != nil {
		_c.SetOrderIndex(*v)
	}
	return _c
}

// SetIsPinned sets the "is_pinned" field.
func (_c *WorkspaceTabCreate) SetIsPinned(v bool) *WorkspaceTabCreate {
	_c.mutation.SetIsPinned(v)
	return _c
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_c *WorkspaceTabCreate) SetNillableIsPinned(v *bool) *WorkspaceTabCreate {
	if v != nil {
		_c.SetIsPinned(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceTabCreate) SetCreatedAt(v time.Time) *WorkspaceTabCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceTabCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceTabCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceTabCreate) SetUpdatedAt(v time.Time) *WorkspaceTabCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceTabCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceTabCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkspaceTabCreate) SetID(v string) *WorkspaceTabCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *WorkspaceTabCreate) SetWorkspace(v *Workspace) *WorkspaceTabCreate {
	return _c.SetWorkspaceID(v.ID)
}

// Mutation returns the WorkspaceTabMutation object of the builder.
func (_c *WorkspaceTabCreate) Mutation() *WorkspaceTabMutation {
	return _c.mutation
}

// Save creates the WorkspaceTab in the database.
func (_c *WorkspaceTabCreate) Save(ctx context.Context) (*WorkspaceTab, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceTabCreate) SaveX(ctx context.Context) *WorkspaceTab {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceTabCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceTabCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceTabCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := workspacetab.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.RunID(); !ok {
		v := workspacetab.DefaultRunID
		_c.mutation.SetRunID(v)
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		v := workspacetab.DefaultOrderIndex
		_c.mutation.SetOrderIndex(v)
	}
	if _, ok := _c.mutation.IsPinned(); !ok {
		v := workspacetab.DefaultIsPinned
		_c.mutation.SetIsPinned(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspacetab.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspacetab.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceTabCreate) check() error {
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WorkspaceTab.workspace_id"`)}
	}
	if v, ok := _c.mutation.WorkspaceID(); ok {
		if err := workspacetab.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceTab.workspace_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "WorkspaceTab.title"`)}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "WorkspaceTab.run_id"`)}
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		return &ValidationError{Name: "order_index", err: errors.New(`ent: missing required field "WorkspaceTab.order_index"`)}
	}
	if _, ok := _c.mutation.IsPinned(); !ok {
		return &ValidationError{Name: "is_pinned", err: errors.New(`ent: missing required field "WorkspaceTab.is_pinned"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkspaceTab.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkspaceTab.updated_at"`)}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "WorkspaceTab.workspace"`)}
	}
	return nil
}

func (_c *WorkspaceTabCreate) sqlSave(ctx context.Context) (*WorkspaceTab, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WorkspaceTab.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceTabCreate) createSpec() (*WorkspaceTab, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkspaceTab{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspacetab.Table, sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(workspacetab.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(workspacetab.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(workspacetab.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if value, ok := _c.mutation.IsPinned(); ok {
		_spec.SetField(workspacetab.FieldIsPinned, field.TypeBool, value)
		_node.IsPinned = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspacetab.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacetab.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacetab.WorkspaceTable,
			Columns: []string{workspacetab.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceTab.Create().
//		SetWorkspaceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceTabUpsert) {
//			SetWorkspaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceTabCreate) OnConflict(opts ...sql.ConflictOption) *WorkspaceTabUpsertOne {
	_c.conflict = opts
	return &WorkspaceTabUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceTab.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceTabCreate) OnConflictColumns(columns ...string) *WorkspaceTabUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceTabUpsertOne{
		create: _c,
	}
}

type (
	// WorkspaceTabUpsertOne is the builder for "upsert"-ing
	//  one WorkspaceTab node.
	WorkspaceTabUpsertOne struct {
		create *WorkspaceTabCreate
	}

	// WorkspaceTabUpsert is the "OnConflict" setter.
	WorkspaceTabUpsert struct {
		*sql.UpdateSet
	}
)

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceTabUpsert) SetWorkspaceID(v string) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateWorkspaceID() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldWorkspaceID)
	return u
}

// SetTitle sets the "title" field.
func (u *WorkspaceTabUpsert) SetTitle(v string) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateTitle() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldTitle)
	return u
}

// SetRunID sets the "run_id" field.
func (u *WorkspaceTabUpsert) SetRunID(v string) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateRunID() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldRunID)
	return u
}

// SetOrderIndex sets the "order_index" field.
func (u *WorkspaceTabUpsert) SetOrderIndex(v int) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldOrderIndex, v)
	return u
}

// UpdateOrderIndex sets the "order_index" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateOrderIndex() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldOrderIndex)
	return u
}

// AddOrderIndex adds v to the "order_index" field.
func (u *WorkspaceTabUpsert) AddOrderIndex(v int) *WorkspaceTabUpsert {
	u.Add(workspacetab.FieldOrderIndex, v)
	return u
}

// SetIsPinned sets the "is_pinned" field.
func (u *WorkspaceTabUpsert) SetIsPinned(v bool) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldIsPinned, v)
	return u
}

// UpdateIsPinned sets the "is_pinned" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateIsPinned() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldIsPinned)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *WorkspaceTabUpsert) SetCreatedAt(v time.Time) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateCreatedAt() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceTabUpsert) SetUpdatedAt(v time.Time) *WorkspaceTabUpsert {
	u.Set(workspacetab.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceTabUpsert) UpdateUpdatedAt() *WorkspaceTabUpsert {
	u.SetExcluded(workspacetab.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.WorkspaceTab.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workspacetab.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkspaceTabUpsertOne) UpdateNewValues() *WorkspaceTabUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(workspacetab.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceTab.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkspaceTabUpsertOne) Ignore() *WorkspaceTabUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceTabUpsertOne) DoNothing() *WorkspaceTabUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceTabCreate.OnConflict
// documentation for more info.
func (u *WorkspaceTabUpsertOne) Update(set func(*WorkspaceTabUpsert)) *WorkspaceTabUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceTabUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceTabUpsertOne) SetWorkspaceID(v string) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateWorkspaceID() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetTitle sets the "title" field.
func (u *WorkspaceTabUpsertOne) SetTitle(v string) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateTitle() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateTitle()
	})
}

// SetRunID sets the "run_id" field.
func (u *WorkspaceTabUpsertOne) SetRunID(v string) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateRunID() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateRunID()
	})
}

// SetOrderIndex sets the "order_index" field.
func (u *WorkspaceTabUpsertOne) SetOrderIndex(v int) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetOrderIndex(v)
	})
}

// AddOrderIndex adds v to the "order_index" field.
func (u *WorkspaceTabUpsertOne) AddOrderIndex(v int) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.AddOrderIndex(v)
	})
}

// UpdateOrderIndex sets the "order_index" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateOrderIndex() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateOrderIndex()
	})
}

// SetIsPinned sets the "is_pinned" field.
func (u *WorkspaceTabUpsertOne) SetIsPinned(v bool) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetIsPinned(v)
	})
}

// UpdateIsPinned sets the "is_pinned" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateIsPinned() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateIsPinned()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *WorkspaceTabUpsertOne) SetCreatedAt(v time.Time) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateCreatedAt() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceTabUpsertOne) SetUpdatedAt(v time.Time) *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceTabUpsertOne) UpdateUpdatedAt() *WorkspaceTabUpsertOne {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceTabUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceTabCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceTabUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkspaceTabUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WorkspaceTabUpsertOne.ID is not supported by MySQL driver. Use WorkspaceTabUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkspaceTabUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkspaceTabCreateBulk is the builder for creating many WorkspaceTab entities in bulk.
type WorkspaceTabCreateBulk struct {
	config
	err      error
	builders []*WorkspaceTabCreate
	conflict []sql.ConflictOption
}

// Save creates the WorkspaceTab entities in the database.
func (_c *WorkspaceTabCreateBulk) Save(ctx context.Context) ([]*WorkspaceTab, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkspaceTab, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceTabMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceTabCreateBulk) SaveX(ctx context.Context) []*WorkspaceTab {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceTabCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceTabCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceTab.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceTabUpsert) {
//			SetWorkspaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceTabCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkspaceTabUpsertBulk {
	_c.conflict = opts
	return &WorkspaceTabUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceTab.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceTabCreateBulk) OnConflictColumns(columns ...string) *WorkspaceTabUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceTabUpsertBulk{
		create: _c,
	}
}

// WorkspaceTabUpsertBulk is the builder for "upsert"-ing
// a bulk of WorkspaceTab nodes.
type WorkspaceTabUpsertBulk struct {
	create *WorkspaceTabCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WorkspaceTab.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workspacetab.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkspaceTabUpsertBulk) UpdateNewValues() *WorkspaceTabUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(workspacetab.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceTab.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkspaceTabUpsertBulk) Ignore() *WorkspaceTabUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceTabUpsertBulk) DoNothing() *WorkspaceTabUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceTabCreateBulk.OnConflict
// documentation for more info.
func (u *WorkspaceTabUpsertBulk) Update(set func(*WorkspaceTabUpsert)) *WorkspaceTabUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceTabUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceTabUpsertBulk) SetWorkspaceID(v string) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateWorkspaceID() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetTitle sets the "title" field.
func (u *WorkspaceTabUpsertBulk) SetTitle(v string) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateTitle() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateTitle()
	})
}

// SetRunID sets the "run_id" field.
func (u *WorkspaceTabUpsertBulk) SetRunID(v string) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateRunID() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateRunID()
	})
}

// SetOrderIndex sets the "order_index" field.
func (u *WorkspaceTabUpsertBulk) SetOrderIndex(v int) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetOrderIndex(v)
	})
}

// AddOrderIndex adds v to the "order_index" field.
func (u *WorkspaceTabUpsertBulk) AddOrderIndex(v int) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.AddOrderIndex(v)
	})
}

// UpdateOrderIndex sets the "order_index" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateOrderIndex() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateOrderIndex()
	})
}

// SetIsPinned sets the "is_pinned" field.
func (u *WorkspaceTabUpsertBulk) SetIsPinned(v bool) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetIsPinned(v)
	})
}

// UpdateIsPinned sets the "is_pinned" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateIsPinned() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateIsPinned()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *WorkspaceTabUpsertBulk) SetCreatedAt(v time.Time) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateCreatedAt() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceTabUpsertBulk) SetUpdatedAt(v time.Time) *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceTabUpsertBulk) UpdateUpdatedAt() *WorkspaceTabUpsertBulk {
	return u.Update(func(s *WorkspaceTabUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceTabUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkspaceTabCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceTabCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceTabUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
