// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/predicate"
	"insightify/internal/gateway/ent/workspace"
	"insightify/internal/gateway/ent/workspacetab"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceTabUpdate is the builder for updating WorkspaceTab entities.
type WorkspaceTabUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceTabMutation
}

// Where appends a list predicates to the WorkspaceTabUpdate builder.
func (_u *WorkspaceTabUpdate) Where(ps ...predicate.WorkspaceTab) *WorkspaceTabUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkspaceTabUpdate) SetWorkspaceID(v string) *WorkspaceTabUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkspaceTabUpdate) SetNillableWorkspaceID(v *string) *WorkspaceTabUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WorkspaceTabUpdate) SetTitle(v string) *WorkspaceTabUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WorkspaceTabUpdate) SetNillableTitle(v *string) *WorkspaceTabUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *WorkspaceTabUpdate) SetRunID(v string) *WorkspaceTabUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *WorkspaceTabUpdate) SetNillableRunID(v *string) *WorkspaceTabUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *WorkspaceTabUpdate) SetOrderIndex(v int) *WorkspaceTabUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *WorkspaceTabUpdate) SetNillableOrderIndex(v *int) *WorkspaceTabUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *WorkspaceTabUpdate) AddOrderIndex(v int) *WorkspaceTabUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *WorkspaceTabUpdate) SetIsPinned(v bool) *WorkspaceTabUpdate {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *WorkspaceTabUpdate) SetNillableIsPinned(v *bool) *WorkspaceTabUpdate {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceTabUpdate) SetCreatedAt(v time.Time) *WorkspaceTabUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceTabUpdate) SetNillableCreatedAt(v *time.Time) *WorkspaceTabUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceTabUpdate) SetUpdatedAt(v time.Time) *WorkspaceTabUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *WorkspaceTabUpdate) SetWorkspace(v *Workspace) *WorkspaceTabUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the WorkspaceTabMutation object of the builder.
func (_u *WorkspaceTabUpdate) Mutation() *WorkspaceTabMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *WorkspaceTabUpdate) ClearWorkspace() *WorkspaceTabUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceTabUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceTabUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceTabUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceTabUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceTabUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspacetab.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceTabUpdate) check() error {
	if v, ok := _u.mutation.WorkspaceID(); ok {
		if err := workspacetab.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceTab.workspace_id": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceTab.workspace"`)
	}
	return nil
}

func (_u *WorkspaceTabUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacetab.Table, workspacetab.Columns, sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(workspacetab.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(workspacetab.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(workspacetab.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(workspacetab.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(workspacetab.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspacetab.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacetab.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacetab.WorkspaceTable,
			Columns: []string{workspacetab.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacetab.WorkspaceTable,
			Columns: []string{workspacetab.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacetab.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceTabUpdateOne is the builder for updating a single WorkspaceTab entity.
type WorkspaceTabUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceTabMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkspaceTabUpdateOne) SetWorkspaceID(v string) *WorkspaceTabUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkspaceTabUpdateOne) SetNillableWorkspaceID(v *string) *WorkspaceTabUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WorkspaceTabUpdateOne) SetTitle(v string) *WorkspaceTabUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WorkspaceTabUpdateOne) SetNillableTitle(v *string) *WorkspaceTabUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *WorkspaceTabUpdateOne) SetRunID(v string) *WorkspaceTabUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *WorkspaceTabUpdateOne) SetNillableRunID(v *string) *WorkspaceTabUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *WorkspaceTabUpdateOne) SetOrderIndex(v int) *WorkspaceTabUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *WorkspaceTabUpdateOne) SetNillableOrderIndex(v *int) *WorkspaceTabUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *WorkspaceTabUpdateOne) AddOrderIndex(v int) *WorkspaceTabUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *WorkspaceTabUpdateOne) SetIsPinned(v bool) *WorkspaceTabUpdateOne {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *WorkspaceTabUpdateOne) SetNillableIsPinned(v *bool) *WorkspaceTabUpdateOne {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceTabUpdateOne) SetCreatedAt(v time.Time) *WorkspaceTabUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceTabUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkspaceTabUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceTabUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceTabUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *WorkspaceTabUpdateOne) SetWorkspace(v *Workspace) *WorkspaceTabUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the WorkspaceTabMutation object of the builder.
func (_u *WorkspaceTabUpdateOne) Mutation() *WorkspaceTabMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *WorkspaceTabUpdateOne) ClearWorkspace() *WorkspaceTabUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// Where appends a list predicates to the WorkspaceTabUpdate builder.
func (_u *WorkspaceTabUpdateOne) Where(ps ...predicate.WorkspaceTab) *WorkspaceTabUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceTabUpdateOne) Select(field string, fields ...string) *WorkspaceTabUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkspaceTab entity.
func (_u *WorkspaceTabUpdateOne) Save(ctx context.Context) (*WorkspaceTab, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceTabUpdateOne) SaveX(ctx context.Context) *WorkspaceTab {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceTabUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceTabUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceTabUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspacetab.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceTabUpdateOne) check() error {
	if v, ok := _u.mutation.WorkspaceID(); ok {
		if err := workspacetab.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "WorkspaceTab.workspace_id": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceTab.workspace"`)
	}
	return nil
}

func (_u *WorkspaceTabUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceTab, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacetab.Table, workspacetab.Columns, sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceTab.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspacetab.FieldID)
		for _, f := range fields {
			if !workspacetab.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspacetab.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(workspacetab.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(workspacetab.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(workspacetab.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(workspacetab.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(workspacetab.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspacetab.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacetab.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacetab.WorkspaceTable,
			Columns: []string{workspacetab.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacetab.WorkspaceTable,
			Columns: []string{workspacetab.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkspaceTab{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacetab.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
