// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"insightify/internal/gateway/ent/predicate"
	"insightify/internal/gateway/ent/workspacetab"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceTabDelete is the builder for deleting a WorkspaceTab entity.
type WorkspaceTabDelete struct {
	config
	hooks    []Hook
	mutation *WorkspaceTabMutation
}

// Where appends a list predicates to the WorkspaceTabDelete builder.
func (_d *WorkspaceTabDelete) Where(ps ...predicate.WorkspaceTab) *WorkspaceTabDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkspaceTabDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceTabDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkspaceTabDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workspacetab.Table, sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkspaceTabDeleteOne is the builder for deleting a single WorkspaceTab entity.
type WorkspaceTabDeleteOne struct {
	_d *WorkspaceTabDelete
}

// Where appends a list predicates to the WorkspaceTabDelete builder.
func (_d *WorkspaceTabDeleteOne) Where(ps ...predicate.WorkspaceTab) *WorkspaceTabDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkspaceTabDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workspacetab.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceTabDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
