// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightify/internal/gateway/ent/predicate"
	"insightify/internal/gateway/ent/workspace"
	"insightify/internal/gateway/ent/workspacetab"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WorkspaceUpdate) SetProjectID(v string) *WorkspaceUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableProjectID(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WorkspaceUpdate) SetName(v string) *WorkspaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableName(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetActiveTabID sets the "active_tab_id" field.
func (_u *WorkspaceUpdate) SetActiveTabID(v string) *WorkspaceUpdate {
	_u.mutation.SetActiveTabID(v)
	return _u
}

// SetNillableActiveTabID sets the "active_tab_id" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableActiveTabID(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetActiveTabID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceUpdate) SetCreatedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableCreatedAt(v *time.Time) *WorkspaceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdate) SetUpdatedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTabIDs adds the "tabs" edge to the WorkspaceTab entity by IDs.
func (_u *WorkspaceUpdate) AddTabIDs(ids ...string) *WorkspaceUpdate {
	_u.mutation.AddTabIDs(ids...)
	return _u
}

// AddTabs adds the "tabs" edges to the WorkspaceTab entity.
func (_u *WorkspaceUpdate) AddTabs(v ...*WorkspaceTab) *WorkspaceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTabIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// ClearTabs clears all "tabs" edges to the WorkspaceTab entity.
func (_u *WorkspaceUpdate) ClearTabs() *WorkspaceUpdate {
	_u.mutation.ClearTabs()
	return _u
}

// RemoveTabIDs removes the "tabs" edge to WorkspaceTab entities by IDs.
func (_u *WorkspaceUpdate) RemoveTabIDs(ids ...string) *WorkspaceUpdate {
	_u.mutation.RemoveTabIDs(ids...)
	return _u
}

// RemoveTabs removes "tabs" edges to WorkspaceTab entities.
func (_u *WorkspaceUpdate) RemoveTabs(v ...*WorkspaceTab) *WorkspaceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTabIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdate) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := workspace.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Workspace.project_id": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(workspace.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActiveTabID(); ok {
		_spec.SetField(workspace.FieldActiveTabID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TabsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TabsTable,
			Columns: []string{workspace.TabsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTabsIDs(); len(nodes) > 0 && !_u.mutation.TabsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TabsTable,
			Columns: []string{workspace.TabsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TabsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TabsTable,
			Columns: []string{workspace.TabsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetProjectID sets the "project_id" field.
func (_u *WorkspaceUpdateOne) SetProjectID(v string) *WorkspaceUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableProjectID(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WorkspaceUpdateOne) SetName(v string) *WorkspaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableName(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetActiveTabID sets the "active_tab_id" field.
func (_u *WorkspaceUpdateOne) SetActiveTabID(v string) *WorkspaceUpdateOne {
	_u.mutation.SetActiveTabID(v)
	return _u
}

// SetNillableActiveTabID sets the "active_tab_id" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableActiveTabID(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetActiveTabID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceUpdateOne) SetCreatedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTabIDs adds the "tabs" edge to the WorkspaceTab entity by IDs.
func (_u *WorkspaceUpdateOne) AddTabIDs(ids ...string) *WorkspaceUpdateOne {
	_u.mutation.AddTabIDs(ids...)
	return _u
}

// AddTabs adds the "tabs" edges to the WorkspaceTab entity.
func (_u *WorkspaceUpdateOne) AddTabs(v ...*WorkspaceTab) *WorkspaceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTabIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// ClearTabs clears all "tabs" edges to the WorkspaceTab entity.
func (_u *WorkspaceUpdateOne) ClearTabs() *WorkspaceUpdateOne {
	_u.mutation.ClearTabs()
	return _u
}

// RemoveTabIDs removes the "tabs" edge to WorkspaceTab entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveTabIDs(ids ...string) *WorkspaceUpdateOne {
	_u.mutation.RemoveTabIDs(ids...)
	return _u
}

// RemoveTabs removes "tabs" edges to WorkspaceTab entities.
func (_u *WorkspaceUpdateOne) RemoveTabs(v ...*WorkspaceTab) *WorkspaceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTabIDs(ids...)
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Workspace entity.
func (_u *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := workspace.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Workspace.project_id": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(workspace.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActiveTabID(); ok {
		_spec.SetField(workspace.FieldActiveTabID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TabsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TabsTable,
			Columns: []string{workspace.TabsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTabsIDs(); len(nodes) > 0 && !_u.mutation.TabsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TabsTable,
			Columns: []string{workspace.TabsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TabsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TabsTable,
			Columns: []string{workspace.TabsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacetab.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workspace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
